language: python

sudo: false

python:
- '2.7'
addons:
  postgresql: '9.3'

services:
- redis-server

before_script:
- flake8
- export DATABASE_URL=postgres://postgres@localhost/{{ cookiecutter.repo_name }}
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c 'CREATE DATABASE "{{ cookiecutter.repo_name }}";' -U postgres

install:
- pip install -r requirements/test.txt

script:
- python {{ cookiecutter.app_name }}/manage.py test --settings=config.test --configuration=Test

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
deploy:
  provider: heroku
  buildpack: python
  strategy: api
  api_key:
    # travis encrypt $(heroku auth:token) --add deploy.api_key
    secure: <add_heroku_auth_token_here>
  app:
    master: {{ cookiecutter.app_name }}-dev
    qa: {{ cookiecutter.app_name }}-qa
    prod: {{ cookiecutter.app_name }}-prod
  on:
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.github_reponame }}
  run:
    - "python {{ cookiecutter.app_name }}/manage.py migrate"
